language: python
sudo: false
env:
- TOXENV=py33
- TOXENV=py34
install:
- pip install codecov tox
script:
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: ponyriders
  password:
    secure: K7eS0kogb2udlgPclBqqK4/Lw/QkYXl3g/+5LrLf9N5NjE/7Sd/LU42HulGOXOWHxHL8CtZXfvU+8CH3CUap7FNPDKb6e8NGSd85xHbB5q+y4xmUU9kwEdFnp5vfE77RtDYLEEcUi+olwi7nO2HN2LIXj2ytPZgNg/4EzfdOAao=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: ponyriders/django-amazon-price-monitor
    condition: "$TOXENV = py34"
