language: python
sudo: false
env:
- TOXENV=py33
- TOXENV=py34
install:
- pip install codecov tox
script:
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: dArignac
  password:
    secure: ly8i+N1kQ6dRrRuDO5AKwVIqHIs/Ahz5CrsCt8Rbo4bPTS6kSCbqI2N1p6ndG9mQvQ0BcTIIRiXWYuCz2givDSs9Mv8P1u4S0epxVP4DWULg1OOpjqQj14Eo0iNq9erWOmSesXYPytEKq5OO2kRiAIapPBOKm8mWGZxcUtjZl2s=
  skip_cleanup: true
  on:
    tags: true
    repo: ponyriders/django-amazon-price-monitor
    distributions: "sdist bdist_wheel"
    condition: "$TOXENV = py34"
