language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev
install:
  - export CPPFLAGS="-O0"
  - pip install -e .
  - pip install -r requirements_test.txt
env:
  - DB=postgres STAGE=TravisCI
script:
  - flake8 price_monitor --ignore=E501,E128 --exclude=migrations
  - coverage run --branch --source=price_monitor `which django-admin.py` test --settings=price_monitor.test_settings price_monitor -omit="price_monitor/migrations/*"
  - coverage report --omit="price_monitor/migrations/*"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a735b80162941c337934
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
cache: apt
after_success:
  coveralls
