language: python
sudo: false
env:
- TOXENV=py33-django18
- TOXENV=py34-django18
- TOXENV=py34-django19
matrix:
  include:
  - python: 3.5
    env:
    - TOXENV=py35-django19
install:
- pip install codecov tox
script:
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: ponyriders
  password:
    secure: C5my1XZnSk859EXUhsKBCGIP361KioMr+NbsFczLJz+a7gHNCRdAUT3sPMH5crjr9I+3S+i0AxVYBDF+5eN70d2+zOviYoXWSJ+YvVveITODAg5feOgFmwZeP+29NP8I7D42A/hwp6LwFp6EhkhZc1kUAu5ceucDpSzw/4FC6ik=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: ponyriders/django-amazon-price-monitor
    condition: "$TOXENV = py34-django18"
