language: python
sudo: false
matrix:
  include:
  - python: 3.3
    env:
    - TOXENV=py33-django1.8
  - python: 3.4
    env:
    - TOXENV=py34-django1.8
  - python: 3.4
    env:
    - TOXENV=py34-django1.9
  - python: 3.4
    env:
    - TOXENV=py34-django1.10
  - python: 3.4
    env:
    - TOXENV=py34-django1.11
  - python: 3.5
    env:
    - TOXENV=py35-django1.9
  - python: 3.5
    env:
    - TOXENV=py35-django1.10
  - python: 3.5
    env:
    - TOXENV=py35-django1.11
  - python: 3.6
    env:
    - TOXENV=py36-django1.11
install:
- pip install codecov tox
script:
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: ponyriders
  password:
    secure: n04DQkYdiwg+XLVfJd/O3Jil7kUV1GeLK/gqTgAjOlpXmChhI3+2Xzg8hKoWYmtxXLqZu0zpvepHVi/y5Xz2R1va+eNjnQ9XKzZBt6t40+YaMKpUTZsP0fGocJr0imxuqmOOV8YJ7cZ3r4eX+4aUMMq2tE2j6b37MczTfBw1YmM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: ponyriders/django-amazon-price-monitor
    condition: "$TOXENV = py35-django1.11"
