language: python
sudo: false
env:
- TOXENV=py33
- TOXENV=py34
install:
- pip install codecov tox
script:
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: ponyriders
  password:
    secure: KOzm1O2fAzo8fcEDoCRjz6NVSS8vxzEBU8qWsTOKPf+tm7kjs7nlTi2kGsL7oFDHkYn99+OXXi6cfGawd/Jm7gIXrh1Lcgjg74OmkYIyds8LRXWBzJm6q94SMLGcVKbRGY/qSaN0Z79dwp3Wgqus0rxC8dkWcrx+nYxbuamkKMA=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: ponyriders/django-amazon-price-monitor
    condition: "$TOXENV = py34"
