version: '3'
services:
  # database container
  db:
    image: postgres:9
    env_file: compose.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  # redis for celery
  redis:
    image: redis:3

  # web container with Django project
  web:
    build: ./web
    image: pricemonitor/web
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: compose.env
    command: /srv/web_run.sh
    volumes:
      - ./logs:/srv/logs
      - ./media:/srv/media
      - ./web/project:/srv/project
      - ../:/srv/pricemonitor
  
  # celery container
  celery:
    build: ./web
    image: pricemonitor/web
    depends_on:
      - redis
    env_file: compose.env
    command: /srv/celery_run.sh
    volumes:
      - ./web/project:/srv/project
      - ../:/srv/pricemonitor
